apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
spec:
  selector:
    matchLabels:
      app: bot
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: 700935310038.dkr.ecr.eu-west-1.amazonaws.com/tamir/jenkins/main/bot:1.0.162
          ports:
            - containerPort: 80
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: env-cm
                  key: ENV
