name:
on:
  workflow_dispatch:
      

jobs:
  build-docker:
    runs-on: ['self-hosted', 'Linux' , 'X64' ]
    steps:
      - name:
        run: |
          docker build -f bot/Dockerfile -t bot:test .