name:
on:
  workflow_dispatch:
      

jobs:
  build-docker:
    runs-on: ['self-hosted', 'Linux' , 'X64']
    steps:
      - uses: actions/checkout@v3
      - name:
        run: |
          whoami
          docker build -f bot/Dockerfile -t bot:test .