name: bot-ci
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region'
        type: choice
        options:
          - ' '
          - eu-west-1
          - us-east-1

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true


env:
  AWS_REGION_DEFAULT: eu-west-1
  DOCKER_REGISTRY: 700935310038.dkr.ecr.eu-west-1.amazonaws.com
  DOCKER_NAMESPACE: tamir

jobs:
  build-docker:
    runs-on: ['self-hosted', 'Linux' , 'X64']
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region || env.AWS_REGION_DEFAULT }}
      
      - name: Set Env Varibles
        run: |
          version=$(cat bot/VERSION)
          echo "DOCKER_IMG=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${{ github.ref_name }}/bot:${version}" >> $GITHUB_ENV
      
      - name: Docker Build
        run: |
          docker build -f bot/Dockerfile -t ${{ env.DOCKER_IMG }} .
      
      - uses: int128/create-ecr-repository-action@v1
        if: github.ref_name == 'main'
        with:
          repository: ${{ env.DOCKER_NAMESPACE }}

      - name: Docker Push
        if: github.ref_name == 'main'
        run: |
          docker push ${{ env.DOCKER_IMG }}

  # update-helm:
  #   runs-on: ['self-hosted', 'Linux' , 'X64']
  #   steps:
  #     - uses: actions/checkout@v3