name: bot-ci
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region'
        type: choice
        options:
          - ' '
          - eu-west-1
          - us-east-1

env:
  AWS_REGION_DEFAULT: eu-west-1
  DOCKER_REGISTRY: 700935310038.dkr.ecr.eu-west-1.amazonaws.com
  DOCKER_NAMESPACE: tamir

jobs:
  build-docker:
    runs-on: ['self-hosted', 'Linux' , 'X64']
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region || env.AWS_REGION_DEFAULT }}
      
      - name: Set Env Varibles
        run: |
          version=$(cat bot/VERSION)
          echo "DOCKER_IMG=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${{ github.ref }}/bot:${version}" >> GITHUB_ENV
      
      - name: docker build
        run: |
          docker build -f bot/Dockerfile -t ${DOCKER_IMG} .

      - name: docker push
        run: |
          docker push -f bot/Dockerfile -t bot:test .

  # update-helm:
  #   runs-on: ['self-hosted', 'Linux' , 'X64']
  #   steps:
  #     - uses: actions/checkout@v3